### Libraries for scientific research

In [1]:
import numpy

In [3]:
numpy.loadtxt(fname='data/inflammation-01.csv',delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [5]:
arthritis=numpy.loadtxt(fname='data/inflammation-01.csv',delimiter=',')

In [7]:
print(arthritis)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [8]:
print(type(arthritis))


<class 'numpy.ndarray'>


In [10]:
print(arthritis.dtype)
print(arthritis.shape)

float64
(60, 40)


In [11]:
print("first value in arthritis:", arthritis[0,0])

first value in arthritis: 0.0


In [12]:
corner=arthritis[:3,36:]

In [13]:
print(corner)

[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [16]:
a='oxygen'
print(a[1:4])

xyg


## Operation

In [17]:
double_arthritis = arthritis*2

In [20]:
print("original")
print(arthritis[:3,36:])
print("double")
print(double_arthritis[:3,36:])

original
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]
double
[[4. 6. 0. 0.]
 [2. 2. 0. 2.]
 [4. 4. 2. 2.]]


In [21]:
triple_arthritis=double_arthritis+arthritis

In [22]:
print(triple_arthritis[:3,36:])

[[6. 9. 0. 0.]
 [3. 3. 0. 3.]
 [6. 6. 3. 3.]]


## Methods(verbs)

In [23]:
print(arthritis.mean())

6.14875


In [24]:
print("maximum inflammation:",arthritis.max())
print("minimum inflammation:",arthritis.min())
print("standard deviation:",arthritis.std())

maximum inflammation: 20.0
minimum inflammation: 0.0
standard deviation: 4.613833197118566


In [25]:
arthritis.size

2400

In [26]:
print("maximum inflammation for patient 2")

maximum inflammation for patient 2


In [29]:
print((arthritis.std(axis=1)).mean())

4.579294680644961
